if (! ("lattice" %in% installed.packages()))
	install.packages("lattice")
library("lattice")
if (! ("xtable" %in% installed.packages()))
	install.packages("xtable")
library("xtable")
if (! ("pastecs" %in% installed.packages()))
	install.packages("pastecs")
library("pastecs")
if (! ("pracma" %in% installed.packages()))
	install.packages("pracma")
library("pracma")
