if (! ("lattice" %in% installed.packages()))
	install.packages("lattice", repos = "https://cloud.r-project.org")
library("lattice")
if (! ("xtable" %in% installed.packages()))
	install.packages("xtable", repos = "https://cloud.r-project.org")
library("xtable")
if (! ("pastecs" %in% installed.packages()))
	install.packages("pastecs", repos = "https://cloud.r-project.org")
library("pastecs")
if (! ("pracma" %in% installed.packages()))
	install.packages("pracma", repos = "https://cloud.r-project.org")
library("pracma")
