set.seed(123)
A <- c(2, 2, 4, 4, 9, 9)
B <- c(1, 1, 6, 6, 8, 8)
C <- c(3, 3, 5, 5, 7, 7)
n <- 1000
rollA <- sample(A, n, replace=TRUE)
rollB <- sample(B, n, replace=TRUE)
rollC <- sample(C, n, replace=TRUE)
ab = mean(rollA > rollB)
bc = mean(rollB > rollC)
ca = mean(rollC > rollA)
cat("The proportion that Die A gave a value greater than Die B:", ab, "\n")
cat("The proportion that Die B gave a value greater than Die C:", bc, "\n")
cat("The proportion that Die C gave a value greater than Die A:", ca, "\n")
